import { logger } from '../lib/logger';
import { callSessionManager } from '../telephony/CallSessionManager';
import { memoryManager } from './MemoryManager';
import { promptBuilder } from './PromptBuilder';
import { contextRetriever } from './ContextRetriever';
import { chatCompletion, streamChatCompletion, ChatMessage } from '../lib/groq';
import { callEventEmitter } from '../realtime/CallEventEmitter';
import { prisma } from '../lib/prisma';

export class ConversationEngine {
  /**
   * Main entry point for transcribed audio text during a call.
   * Takes the user's spoken text, processes it through the LLM, and returns the AI's response text.
   */
  async processUserInput(callId: string, userInput: string, fallbackEmployeeId?: string): Promise<string> {
    try {
      const session = await callSessionManager.getSession(callId);
      let employeeId = session?.employeeId || fallbackEmployeeId;

      if (!employeeId) {
        const emp = await prisma.aIEmployee.findFirst({
          where: { status: 'ACTIVE' },
          orderBy: { createdAt: 'desc' }
        }).catch(() => null);
        employeeId = emp?.id || '';
      }

      // 1. Add user input to memory
      await memoryManager.addMessage(callId, { role: 'user', content: userInput });

      const isUuid = (str: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(str);

      // Emit live transcript for caller
      try {
        const call = await prisma.call.findFirst({
          where: isUuid(callId)
            ? { OR: [{ id: callId }, { twilioCallSid: callId }] }
            : { twilioCallSid: callId },
          select: { organizationId: true, id: true }
        });
        if (call) {
          callEventEmitter.emitLiveTranscript(call.organizationId, call.id, 'user', userInput);
        }
      } catch { /* ignore */ }

      // 2. Retrieve relevant context (RAG)
      const context = await contextRetriever.retrieveContext(employeeId, userInput);

      // 3. Build the prompt
      const systemPrompt = await promptBuilder.buildSystemPrompt(employeeId, context, session?.variables || {});
      const conversationHistory = await memoryManager.getHistory(callId);

      // 4. Call Groq LLM
      const messages: ChatMessage[] = [
        { role: 'system', content: systemPrompt },
        ...conversationHistory.map((h: any) => ({ role: h.role as "user" | "system" | "assistant", content: h.content }))
      ];

      let aiResponse = await chatCompletion(messages);
      aiResponse = (aiResponse || '').trim();

      // Clean up markdown formatting symbols so TTS speaks naturally
      aiResponse = aiResponse
        .replace(/[*_#`~[\]]/g, '')
        .replace(/\n+/g, ' ')
        .trim();

      if (!aiResponse) {
        aiResponse = "I understand. How else can I assist you today?";
      }

      // 5. Add AI response to memory
      await memoryManager.addMessage(callId, { role: 'assistant', content: aiResponse });

      // Emit live transcript for assistant
      try {
        const call = await prisma.call.findFirst({
          where: isUuid(callId)
            ? { OR: [{ id: callId }, { twilioCallSid: callId }] }
            : { twilioCallSid: callId },
          select: { organizationId: true, id: true }
        });
        if (call) {
          callEventEmitter.emitLiveTranscript(call.organizationId, call.id, 'assistant', aiResponse);
        }
      } catch { /* ignore */ }

      return aiResponse;
    } catch (error) {
      logger.error(`Error in ConversationEngine for call ${callId}: ${error}`);
      return "I'm sorry, I'm having trouble processing that right now. Could you repeat?";
    }
  }

  /**
   * Low-latency streaming method that yields clean sentences as they are generated by Groq LLM.
   * This enables parallel TTS generation while tokens are still streaming!
   */
  async processUserInputStreaming(
    callId: string,
    userInput: string,
    fallbackEmployeeId: string | undefined,
    onSentence: (sentence: string, isFinal: boolean) => Promise<void>
  ): Promise<string> {
    try {
      const session = await callSessionManager.getSession(callId);
      let employeeId = session?.employeeId || fallbackEmployeeId;

      if (!employeeId) {
        const emp = await prisma.aIEmployee.findFirst({
          where: { status: 'ACTIVE' },
          orderBy: { createdAt: 'desc' }
        }).catch(() => null);
        employeeId = emp?.id || '';
      }

      // 1. Add user input to memory
      await memoryManager.addMessage(callId, { role: 'user', content: userInput });

      const isUuid = (str: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(str);

      // Emit live transcript for caller
      try {
        const call = await prisma.call.findFirst({
          where: isUuid(callId)
            ? { OR: [{ id: callId }, { twilioCallSid: callId }] }
            : { twilioCallSid: callId },
          select: { organizationId: true, id: true }
        });
        if (call) {
          callEventEmitter.emitLiveTranscript(call.organizationId, call.id, 'user', userInput);
        }
      } catch { /* ignore */ }

      // 2. Retrieve relevant context (RAG)
      const context = await contextRetriever.retrieveContext(employeeId, userInput);

      // 3. Build the prompt
      const systemPrompt = await promptBuilder.buildSystemPrompt(employeeId, context, session?.variables || {});
      const conversationHistory = await memoryManager.getHistory(callId);

      // 4. Stream Groq LLM tokens with sentence-level chunking
      const messages: ChatMessage[] = [
        { role: 'system', content: systemPrompt },
        ...conversationHistory.map((h: any) => ({ role: h.role as "user" | "system" | "assistant", content: h.content }))
      ];

      let fullAiResponse = '';
      let sentenceBuffer = '';

      await streamChatCompletion(messages, {
        maxTokens: 120, // Keep concise for sub-second phone conversation
        onChunk: async (delta: string) => {
          fullAiResponse += delta;
          sentenceBuffer += delta;

          // Check if we hit a sentence terminator: . ! ? or newline followed by space
          const match = sentenceBuffer.match(/^(.*?[.?!;\n]+)(\s+)(.*)$/s);
          if (match) {
            const rawSentence = match[1].trim();
            sentenceBuffer = match[3];

            const cleanSentence = rawSentence
              .replace(/[*_#`~[\]]/g, '')
              .replace(/\n+/g, ' ')
              .trim();

            if (cleanSentence.length > 2) {
              await onSentence(cleanSentence, false);
            }
          }
        }
      });

      // Flush remaining buffer
      const remainingClean = sentenceBuffer
        .replace(/[*_#`~[\]]/g, '')
        .replace(/\n+/g, ' ')
        .trim();

      if (remainingClean.length > 0) {
        await onSentence(remainingClean, true);
      } else {
        await onSentence('', true);
      }

      fullAiResponse = fullAiResponse.replace(/[*_#`~[\]]/g, '').trim();
      if (!fullAiResponse) {
        fullAiResponse = "I understand. How else can I assist you today?";
      }

      // 5. Add AI response to memory
      await memoryManager.addMessage(callId, { role: 'assistant', content: fullAiResponse });

      // Emit live transcript for assistant
      try {
        const call = await prisma.call.findFirst({
          where: isUuid(callId)
            ? { OR: [{ id: callId }, { twilioCallSid: callId }] }
            : { twilioCallSid: callId },
          select: { organizationId: true, id: true }
        });
        if (call) {
          callEventEmitter.emitLiveTranscript(call.organizationId, call.id, 'assistant', fullAiResponse);
        }
      } catch { /* ignore */ }

      return fullAiResponse;
    } catch (error) {
      logger.error(`Error in ConversationEngine streaming for call ${callId}: ${error}`);
      const fallback = "I'm sorry, I'm having trouble processing that right now. Could you repeat?";
      await onSentence(fallback, true);
      return fallback;
    }
  }

  async handleCallStart(callId: string): Promise<string> {
    logger.info(`Conversation started for call ${callId}`);
    return "Hi! Thanks for reaching out. I'm Yuvaraj, your AI Sales Development Representative. How can I help you today?";
  }

  async handleCallEnd(callId: string) {
    logger.info(`Conversation ended for call ${callId}`);
  }
}

export const conversationEngine = new ConversationEngine();
