/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#363025",
        "outline": "#827561",
        "secondary-fixed-dim": "#e4c282",
        "background": "#fff8f2",
        "tertiary-container": "#5bb9ff",
        "on-secondary-fixed-variant": "#5a430f",
        "on-error": "#ffffff",
        "on-primary-container": "#593f00",
        "on-surface-variant": "#504533",
        "surface-container": "#f8ecdd",
        "tertiary-fixed": "#cce5ff",
        "surface-container-low": "#fef2e2",
        "on-tertiary-container": "#00486f",
        "on-secondary-container": "#795f29",
        "secondary-fixed": "#ffdea4",
        "on-primary-fixed-variant": "#5d4200",
        "on-primary": "#ffffff",
        "surface-container-highest": "#ece1d2",
        "secondary": "#745a25",
        "on-background": "#201b12",
        "on-tertiary-fixed-variant": "#004b73",
        "error-container": "#ffdad6",
        "surface-tint": "#7b5800",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#001d31",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#fbefdf",
        "surface-variant": "#ece1d2",
        "on-secondary-fixed": "#261900",
        "surface": "#fff8f2",
        "primary-fixed-dim": "#fbbc29",
        "error": "#ba1a1a",
        "primary-fixed": "#ffdea4",
        "on-primary-fixed": "#261900",
        "primary": "#7b5800",
        "tertiary": "#006397",
        "surface-bright": "#fff8f2",
        "on-surface": "#201b12",
        "primary-container": "#e3a709",
        "outline-variant": "#d4c4ad",
        "inverse-primary": "#fbbc29",
        "surface-dim": "#e4d8c9",
        "surface-container-high": "#f2e7d7",
        "secondary-container": "#ffdb99",
        "tertiary-fixed-dim": "#92ccff"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        xl: "32px",
        xxl: "48px",
        gutter: "24px",
        md: "16px",
        sm: "8px",
        lg: "24px",
        xs: "4px",
        xxxl: "64px",
        unit: "4px",
        margin: "32px"
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "display": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
