import { spawn } from 'child_process';
import { logger } from '../lib/logger';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const ffmpegInstaller = require('@ffmpeg-installer/ffmpeg');
const ffmpegPath: string = ffmpegInstaller.path || 'ffmpeg';

export class AudioProcessor {
  /**
   * Converts an MP3 buffer (generated by TTS) into raw 8000Hz 8-bit mono μ-law (PCMU)
   * which is the exact format expected by Twilio Media Streams over WebSocket.
   */
  async mp3ToMulaw(mp3Buffer: Buffer): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      const proc = spawn(ffmpegPath, [
        '-i', 'pipe:0',
        '-f', 'mulaw',
        '-ar', '8000',
        '-ac', '1',
        'pipe:1',
      ]);

      const chunks: Buffer[] = [];
      proc.stdout.on('data', (d: Buffer) => chunks.push(d));
      proc.stderr.on('data', () => { /* suppress debug output */ });

      proc.on('close', (code) => {
        if (code === 0) {
          resolve(Buffer.concat(chunks));
        } else {
          logger.error(`[AudioProcessor] ffmpeg mp3ToMulaw failed with code ${code}`);
          reject(new Error(`ffmpeg exited with code ${code}`));
        }
      });

      proc.on('error', (err) => {
        logger.error(`[AudioProcessor] ffmpeg error: ${err.message}`);
        reject(err);
      });

      proc.stdin.write(mp3Buffer);
      proc.stdin.end();
    });
  }

  /**
   * Converts a raw 8000Hz μ-law buffer (received from Twilio Media Streams)
   * into a 16000Hz 16-bit mono PCM WAV buffer (compatible with Whisper STT).
   */
  async mulawToWav(mulawBuffer: Buffer): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      const proc = spawn(ffmpegPath, [
        '-f', 'mulaw',
        '-ar', '8000',
        '-ac', '1',
        '-i', 'pipe:0',
        '-f', 'wav',
        '-ar', '16000',
        '-ac', '1',
        'pipe:1',
      ]);

      const chunks: Buffer[] = [];
      proc.stdout.on('data', (d: Buffer) => chunks.push(d));
      proc.stderr.on('data', () => { /* suppress debug output */ });

      proc.on('close', (code) => {
        if (code === 0) {
          resolve(Buffer.concat(chunks));
        } else {
          logger.error(`[AudioProcessor] ffmpeg mulawToWav failed with code ${code}`);
          reject(new Error(`ffmpeg exited with code ${code}`));
        }
      });

      proc.on('error', (err) => {
        logger.error(`[AudioProcessor] ffmpeg error: ${err.message}`);
        reject(err);
      });

      proc.stdin.write(mulawBuffer);
      proc.stdin.end();
    });
  }

  /**
   * Decodes a single μ-law byte into a 16-bit signed PCM value [-32768, 32767].
   */
  mulawToLinear(byte: number): number {
    const s = ~byte & 0xff;
    const sign = s & 0x80;
    const exponent = (s >> 4) & 0x07;
    const mantissa = s & 0x0f;
    let sample = ((mantissa << 3) + 0x84) << exponent;
    sample -= 0x84;
    return sign ? -sample : sample;
  }

  /**
   * Computes the RMS energy of a μ-law audio chunk for Voice Activity Detection (VAD).
   */
  getRms(mulawChunk: Buffer): number {
    if (!mulawChunk || mulawChunk.length === 0) return 0;
    let sum = 0;
    for (let i = 0; i < mulawChunk.length; i++) {
      const sample = this.mulawToLinear(mulawChunk[i]);
      sum += sample * sample;
    }
    return Math.sqrt(sum / mulawChunk.length);
  }

  /**
   * Detects if an incoming μ-law chunk contains speech above a background threshold.
   */
  isSpeech(mulawChunk: Buffer, threshold: number = 400): boolean {
    return this.getRms(mulawChunk) > threshold;
  }

  /**
   * Legacy method for backward compatibility
   */
  processForTwilio(pcmBuffer: Buffer): Buffer {
    return pcmBuffer;
  }

  /**
   * Legacy method for backward compatibility
   */
  processForSTT(mulawBase64: string): Buffer {
    return Buffer.from(mulawBase64, 'base64');
  }
}

export const audioProcessor = new AudioProcessor();
